spring.application.name=pedidos-service

# Base de datos RDS MySQL (cloud)
spring.datasource.url=jdbc:mysql://pedidos360-db.cwiau5oiy57r.us-east-1.rds.amazonaws.com:3306/pedidosdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=PedidosDb2026!

# Hibernate crea las tablas automáticamente a partir de tus entidades @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cognito - validacion de JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_UyJcppibf
cognito.app-client-id=2uudamt3adb8a2fpcau89um4v6