spring.application.name=pedidos-service

# Base de datos H2 en memoria (temporal, solo para probar)
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2, para ver las tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate crea las tablas automáticamente a partir de tus entidades @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true